include: package:effective_dart/analysis_options.yaml

linter:
  rules:

    # Use parameter order as in json response
    always_put_required_named_parameters_first: true

    # Util classes are awesome!
    avoid_classes_with_only_static_members: false

    # Make constructors the first thing in every class
    sort_constructors_first: false

    # The new tabs vs. spaces. Choose wisely
    prefer_double_quotes: false
    prefer_single_quotes: false

    # Good packages document everything
    public_member_api_docs: false

    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: false

    # Back to the 80s
    lines_longer_than_80_chars: false

    # CamelCase for file names
    file_names: camelcase

analyzer:
  errors:
    invalid_assignment: warning
    missing_return: error
    always_specify_types: info